# Generated by Django 4.2.1 on 2023-06-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_dopdock'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='dops',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.dopdock'),
        ),
    ]
