# Generated by Django 4.2.1 on 2023-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_people_dops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='dops',
        ),
        migrations.DeleteModel(
            name='Dopdock',
        ),
    ]
