# Generated by Django 4.2.2 on 2023-06-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_people_dops_delete_dopdock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['date_create', 'title'], 'verbose_name': 'Известные люди', 'verbose_name_plural': 'Известные люди'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='people',
            name='author',
            field=models.CharField(max_length=250, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='people',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='people',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='people',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='people',
            name='images',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
    ]
